@startuml

left to right direction

!define model #FCC9B9
!define controller #FFC28B
!define view #7DACCE
!define viewCenter #9DCCEE

class DBAdapter #FBF6F7 {
  - constructor()
  - DBAdapter instance
  - Connection con
  - Statement stm
  + ResultSet getAll(String)
  + ResultSet sendQuery(String)
  + PreparedStatement setPreparedStatement(String)
  + void closeConnection()
  + void closeStatement()
}

class Main {
  + void main()
}

class User model {
  + Integer userId
  + String name
  + String password
  + Date birthday
  + Integer gender
  + constructor(Integer, String, String, Date, Integer)
  + constructor(ResultSet)
}

class Novel model {
  + Integer novelId
  + Integer userId   
  + String title
  + Timestamp date
  + constructor(Integer, Integer, String, Timestamp)
  + constructor(ResultSet)
}

class Text model {
  + Integer textId
  + Integer novelId
  + Integer userId
  + String text
  + Timestamp date
  + constructor(Integer, Integer, Integer, String, Timestamp)
  + constructor(ResultSet)
}

class ReviewText model {
  + Integer reviewTextId
  + Integer userId
  + Integer textId
  + String text
  + Integer score
  + Timestamp date
  + constructor(Integer, Integer, Integer, String, Integer, Timestamp)
  + constructor(ResultSet)
}

class ReviewNovel model {
  + Integer reviewNovelId
  + Integer userId
  + Integer textId
  + String text
  + Integer score
  + Timestamp date
  + constructor(Integer, Integer, Integer, String, Integer, Timestamp)
  + constructor(ResultSet)
}

class View viewCenter {
  # String title
  # String message
  # String inputDescription
  - void clearScreen()
  + constructor()
  + void show()
  + abstract void main()
}

class RegisterView view {
  + constructor()
  + void main()
}

class MainMenuView view {
  + constructor()
  + void main()
}

class NovelListView view {
  + constructor(int page, String s, User user)
  + void main()
  + static View openNovelList(User user)
  - static View changePage(int page, User user)
  - static String formatNovelTitles(ArrayList<Novel>novels, int page)
  - static String repeat(String s, int rep)
  - void registerNovel()
  - void login()
  - void register()
  - static final int NOVELS_PER_PAGE = 10
  - int page
  - LoginView lv
  - User user
  - Boolean registering

}

class NovelView view {
  - constructor(int novelId, int page, String s, View view, User user)
  + void main()
  + static View openNovel(int novelId, View parentView, User user)
  - static View changePage(int novelId, int page, View view, User user)
  - static String formatTexts(ArrayList<Text> texts, int page)
  - void writeText()
  - void login()
  - void write()
  - Novel novel
  - int page
  - View parentView
  - static final int TEXTS_PER_PAGE = 20
  - LoginView lv
  - User user
  - Boolean writing
}

class ReviewNovelView view {
  - constructor(int novelId, int page, String s, View view, User user)
  + void main()
  - static View changePage(int novelId, int page, View view, User user)
  - static String formatReviews(ArrayList<ReviewNovel> reviews, int page)
  - void writeReview()
  - void login()
  - void review()
  - Novel novel
  - int page
  - View parentView
  - static final int REVIEWS_PER_PAGE = 20
  - LoginView lv
  - User user
  - Boolean reviewing
}

class TextDetailView view {
  + constructor(int novelId, int textId, int page , String s, View view, User user)
  + void main()
  + static View openTextDetail(int novelId, int textId, View parentView, User user)
  - static View changePage(int novelId, int textId, int page, View view, User user)
  - static String formatReviews(ArrayList<ReviewText> reviews, int page)
  - void writeReview()
  - void login()
  - void review()
  - Novel novel
  - Text text
  - int page
  - View parentView
  - static final int REVIEWS_PER_PAGE = 20
  - LoginView lv
  - User user
  - Boolean reviewingß
}

class LoginView view {
  + constructor(View parentView)
  + void main()
  + User user
  - View parentView
}

class JoinedUserListView view {
  + JoinedUserListView(int novelId)
  + void main()
}

class ViewController viewCenter {
  - ViewController instance
  - View viewNow
  - View viewNext
  - constructor()
  + ViewController getInstance()
  + void run()
  + void switchView(View)
}

class UserController controller {
  - constructor()
  - UserController instance
  + UserController getInstance()
  + boolean insert(User)
  + User getById(int)
  + User getByName(String)
  + User login(User)
  + ArrayList<User> getAll()
}

class NovelController controller {
  - constructor()
  - NovelController instance
  + NovelController getInstance()
  + boolean insert(Novel)
  + ArrayList<Novel> getAll()
  + ArrayList<Novel> getNovels(int, int)
  + ArrayList<Text> getTexts(int, int, int)
}

class TextController controller {
  - constructor()
  - TextController instance
  + TextController getInstance()
  + boolean insert(Text)
  + ArrayList<Text> getAll()
}

class ReviewNovelController controller {
  - constructor()
  - ReviewNovelController instance
  + ReviewNovelController getInstance()
  + boolean insert(ReviewNovel)
  + ReviewNovel getById(int)
  + ArrayList<ReviewNovel> reviews(int, int, int)
}

class ReviewTextController controller {
  - constructor()
  - ReviewTextController instance
  + ReviewTextController getInstance()
  + boolean insert(ReviewText)
  + ReviewText getById(int)
  + ArrayList<ReviewText> reviews(int, int, int)
}

' Text -- View
' User -- View
' Novel -- View
' ReviewText -- View
' ReviewNovel -- View
Main -- ViewController
ViewController -- View

UserController -up- View
UserController - User
UserController -down- DBAdapter

NovelController -up- View
NovelController - Novel
NovelController -down- DBAdapter

TextController -up- View
TextController - Text
TextController -down- DBAdapter

ReviewTextController -up- View
ReviewTextController - ReviewText
ReviewTextController -down- DBAdapter

ReviewNovelController -up- View
ReviewNovelController - ReviewNovel
ReviewNovelController -down- DBAdapter


View <|-left- RegisterView
View <|-left- LoginView
View <|-left- MainMenuView
View <|-left- NovelListView
View <|-right- NovelView
View <|-right- ReviewNovelView
View <|-right- TextDetailView
View <|-right- JoinedUserListView

@enduml
